#!/usr/bin/env bash

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" # oh-my-zsh
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash # nvm
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2 # asdf

# backup files
for file in .zshrc .gitconfig .gitignore .aliases Brewfile
do
    [[ -f "$HOME/${file}" ]] && mv -f "${file}" "${file}.backup"
done

git clone https://github.com/dracula/zsh.git $HOME/.tmp
git clone --bare https://github.com/vitorsalgado/dotfiles.git $HOME/.dotfiles

# zsh theme
cp $HOME/.tmp/dracula.zsh-theme .oh-my-zsh/custom/themes/dracula.zsh-theme

# dotfiles repository
/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout

touch .gitconfig_local
touch .zshrc_local

brew update
brew upgrade
brew bundle

# cleanup
rm -rf $HOME/.tmp
