[package]
format = "[$symbol$version]($style) "
symbol = ""

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[aws]
symbol = " "

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[java]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[gcloud]
symbol = " "
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
symbol = " "
